//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managementsoftwaredbEntities : DbContext
    {
        public managementsoftwaredbEntities()
            : base("name=managementsoftwaredbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBudgetType> tblBudgetTypes { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblcompanyCategory> tblcompanyCategories { get; set; }
        public virtual DbSet<tblExpectedBudgetLine> tblExpectedBudgetLines { get; set; }
        public virtual DbSet<tblRealBudget> tblRealBudgets { get; set; }
        public virtual DbSet<tblReportType> tblReportTypes { get; set; }
        public virtual DbSet<C__MigrationHistory1> C__MigrationHistory1 { get; set; }
        public virtual DbSet<AspNetRole1> AspNetRole1 { get; set; }
        public virtual DbSet<AspNetUserClaim1> AspNetUserClaim1 { get; set; }
        public virtual DbSet<AspNetUserLogin1> AspNetUserLogin1 { get; set; }
        public virtual DbSet<AspNetUser1> AspNetUser1 { get; set; }
        public virtual DbSet<tblContentPage> tblContentPages { get; set; }
        public virtual DbSet<tblKeyPointBudgetLine> tblKeyPointBudgetLines { get; set; }
        public virtual DbSet<tblKeyPointGroup> tblKeyPointGroups { get; set; }
        public virtual DbSet<tblRealCarCount> tblRealCarCounts { get; set; }
    }
}
