//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeyPointGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKeyPointGroup()
        {
            this.tblKeyPointBudgetLines = new HashSet<tblKeyPointBudgetLine>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<bool> isnetProfitKey { get; set; }
        public Nullable<bool> isBusinessDevKey { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKeyPointBudgetLine> tblKeyPointBudgetLines { get; set; }
    }
}
