//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeyPointBudgetLine
    {
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> keypointId { get; set; }
        public Nullable<System.DateTime> creatDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblKeyPointGroup tblKeyPointGroup { get; set; }
    }
}
